packages:
  - "server"
  - "desktop"
  - "packages/*"
  - "ui-design"
  - "demos/*"
  - "../../electron-plugin/packages/electron-core-wireguard"
  - "../../electron-plugin/packages/wireguard-engines/*"
