[Interface]
Address = 10.7.0.3/24
DNS = 8.8.8.8,8.8.4.4
PrivateKey = 8OUXAo9+VaBQPYXNTGjOcGolgzB5YEXF1LjX44pB3k4=

[Peer]
PublicKey = z9e7TF3/xhtUg+ISwlX5UjC/9yly540UrvW0xQ1goTo=
PresharedKey = lANp1JwrklEQpBJ8T8JAu6PmYjdlp7QS23VHXESuTu8=
AllowedIPs = 0.0.0.0/0
Endpoint = 23.225.161.60:51239
PersistentKeepalive = 25
