apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mx-awx
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.19.1
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1
patches:
  - target:
      kind: Deployment
      name: awx-operator-controller-manager
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0
      - op: remove
        path: /spec/template/spec/imagePullSecrets
