#!/usr/bin/env node
import { writeFileSync, renameSync, rmSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PROFILE, readProfile } from './identity-profile.mjs';

export function renderInternalIngress(entry) {
  const host = origin => new URL(origin).hostname;
  const forward = `proxy_pass ${entry.transportOrigin};\n        proxy_http_version 1.1;\n        proxy_set_header Host $host;\n        proxy_set_header Connection "";\n        proxy_set_header X-Forwarded-Proto https;\n        proxy_set_header X-MX-Identity-Gateway "${entry.ingressToken}";\n        proxy_set_header X-MX-Client-IP $http_x_real_ip;\n        proxy_connect_timeout 5s;\n        proxy_read_timeout 60s;\n        proxy_buffering off;`;
  const common = `listen 80;\n    # Only the fixed Domestic WireGuard peer may supply client-IP provenance.\n    allow 10.88.0.1;\n    deny all;\n    client_max_body_size 10m;\n    access_log off;`;
  return `# Generated by ops identity public. Contains a private gateway credential: root 0600, never commit.\nserver {\n    ${common}\n    server_name ${host(entry.origin)};\n    location ^~ /identity/ {\n        ${forward}\n    }\n    location / { return 404; }\n}\nserver {\n    ${common}\n    server_name ${host(entry.adminOrigin)};\n    location = / { return 302 /admin/; }\n    location = /admin { return 302 /admin/; }\n${['/admin/','/auth/admin/','/admin-api/'].map(path=>`    location ^~ ${path} {\n        ${forward}\n    }`).join('\n')}\n    location / { return 404; }\n}\n`;
}

// Derived file only: never rotate credentials or reload Nginx here.
export function writeInternalIngress(profile, file = PROFILE) {
  if (!profile?.publicEntry) throw new Error('尚未登记公网身份入口。请先运行 ops identity public https://auth.minsight-ai.com https://launcher.minsight-ai.com https://hub.minsight-ai.com；原私网配置保持不变。');
  const target = join(dirname(file), 'public-ingress.conf');
  const temporary = `${target}.${randomUUID()}.tmp`;
  try {
    writeFileSync(temporary, renderInternalIngress(profile.publicEntry), { mode: 0o600, flag: 'wx' });
    renameSync(temporary, target);
  } finally { rmSync(temporary, { force: true }); }
  return target;
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    if (process.argv.length !== 2) throw new Error('用法：bash scripts/manage.sh ops identity ingress');
    console.log(`已按原身份档案生成：${writeInternalIngress(readProfile())}`);
    console.log('未修改密钥、账号或服务。请在内网 Nginx 安装配置并检查后 reload；不要公开文件内容。');
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
