-- 2026-10-08: explicitly requested by the user to run during the next deploy.
-- One previously paid, verified response only. No upstream calls, billing
-- changes, secret rotation, automatic platform-wide grants or identity changes.
-- runMigrations executes this entire file and its receipt in one transaction.
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '60s';

CREATE OR REPLACE FUNCTION core.weibo_long_text_preview_of(full_body text, preview text)
RETURNS boolean LANGUAGE sql IMMUTABLE STRICT AS $fn$
  SELECT preview ~ '[[:space:]​‌‍﻿]*(?:[.。…]+[[:space:]]*)?展开(全文)?[cC]?[[:space:]​‌‍﻿]*$'
    AND length(prefix) >= 40 AND length(content) > length(prefix)
    AND starts_with(content, prefix)
  FROM (SELECT
    regexp_replace(regexp_replace(preview,
      '[[:space:]​‌‍﻿]*(?:[.。…]+[[:space:]]*)?展开(全文)?[cC]?[[:space:]​‌‍﻿]*$', ''),
      '[[:space:]​‌‍﻿]', '', 'g') AS prefix,
    regexp_replace(full_body, '[[:space:]​‌‍﻿]', '', 'g') AS content) normalized;
$fn$;

-- Installed before the data change, in the same transaction. This protects
-- against old ingest workers during migrate-before-rollout as well as new ones.
CREATE OR REPLACE FUNCTION core.preserve_verified_weibo_long_text()
RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  IF NEW.deleted_at IS NULL AND OLD.deleted_at IS NULL
     AND NEW.dataset_id = OLD.dataset_id AND NEW.platform = OLD.platform
     AND NEW.object_type = OLD.object_type AND NEW.external_id = OLD.external_id
     AND core.weibo_long_text_preview_of(OLD.body, NEW.body) THEN
    OLD.last_seen_at := GREATEST(OLD.last_seen_at, NEW.last_seen_at);
    RETURN OLD;
  END IF;
  RETURN NEW;
END
$fn$;
DROP TRIGGER IF EXISTS preserve_weibo_5351726865449966 ON core.canonical_records;
CREATE TRIGGER preserve_weibo_5351726865449966
BEFORE UPDATE ON core.canonical_records FOR EACH ROW
WHEN (OLD.id = '34c72b79-f291-4ef7-ad9b-fe62eb03912d'::uuid
  AND OLD.platform = 'weibo'
  AND OLD.extensions #>> '{weiboLongTextRepair,responseSha256}' =
    'b05ecd61c51bb3e51a1fa464e0ffd78e41c10c0b47363a5b07806bee003444dc')
EXECUTE FUNCTION core.preserve_verified_weibo_long_text();

DO $repair$
DECLARE
  target_id constant uuid := '34c72b79-f291-4ef7-ad9b-fe62eb03912d';
  response_hash constant text := 'b05ecd61c51bb3e51a1fa464e0ffd78e41c10c0b47363a5b07806bee003444dc';
  provider_request constant text := '3b57afa7-2664-4dc7-9e4e-b8b5eb9c86be';
  captured_at constant timestamptz := '2026-10-08T05:56:31.007Z';
  exact_bytes bytea := decode($evidence$eyJjb2RlIjoyMDAsInJlcXVlc3RfaWQiOiIzYjU3YWZhNy0yNjY0LTRkYzctOWU0ZS1iOGI1ZWI5Yzg2YmUiLCJtZXNzYWdlIjoiUmVxdWVzdCBzdWNjZXNzZnVsLiBUaGlzIHJlcXVlc3Qgd2lsbCBpbmN1ciBhIGNoYXJnZS4iLCJtZXNzYWdlX3poIjoi6K+35rGC5oiQ5Yqf77yM5pys5qyh6K+35rGC5bCG6KKr6K6h6LS544CCIiwic3VwcG9ydCI6IkRpc2NvcmQ6IGh0dHBzOi8vZGlzY29yZC5nZy9hTUVBUzhYc3Z6IiwidGltZSI6IjIwMjYtMTAtMDcgMjI6NTY6MzAiLCJ0aW1lX3N0YW1wIjoxNzkxNDM4OTkwLCJ0aW1lX3pvbmUiOiJBbWVyaWNhL0xvc19BbmdlbGVzIiwiZG9jcyI6Imh0dHBzOi8vYXBpLnRpa2h1Yi5pby8jL1dlaWJvLVdlYi1WMi1BUEkvZmV0Y2hfcG9zdF9kZXRhaWxfYXBpX3YxX3dlaWJvX3dlYl92Ml9mZXRjaF9wb3N0X2RldGFpbF9nZXQiLCJjYWNoZV9tZXNzYWdlIjoiVGhpcyByZXNwb25zZSBpcyBjYWNoZWQgYW5kIGFjY2Vzc2libGUgdmlhIHRoZSBVUkwgYmVsb3cgZm9yIDI0IGhvdXJzIGF0IG5vIGV4dHJhIGNvc3QuIFRoZSBjYWNoZSBpcyBmb3IgcmVxdWVzdCB0cmFjaW5nIG9ubHkg4oCUIGl0IGRvZXNuJ3QgYWZmZWN0IHRoZSBBUEkncyBkYXRhIGZyZXNobmVzcyBhbmQgd29uJ3QgYmUgcmV0dXJuZWQgdGhyb3VnaCB0aGUgQVBJIGFnYWluLiIsImNhY2hlX21lc3NhZ2VfemgiOiLmnKzmrKHlk43lupTlt7LnvJPlrZjvvIzlj6/pgJrov4fkuIvmlrkgVVJMIOebtOaOpeafpeeci++8jOacieaViOacnyAyNCDlsI/ml7bvvIzorr/pl67nvJPlrZjpk77mjqXml6Dpop3lpJbotLnnlKjjgILnvJPlrZjku4XnlKjkuo7or7fmsYLmuq/mupDvvIzkuI3lvbHlk43mjqXlj6PmlbDmja7nmoTml7bmlYjmgKfvvIzkuZ/kuI3kvJrlho3mrKHpgJrov4fmjqXlj6Pov5Tlm57jgIIiLCJjYWNoZV91cmwiOiJodHRwczovL2NhY2hlLnRpa2h1Yi5pby9hcGkvdjEvY2FjaGUvcHVibGljLzNiNTdhZmE3LTI2NjQtNGRjNy05ZTRlLWI4YjVlYjljODZiZT9zaWduPWQxNmU3MDc4YTU2MTVmYTQyMDQ4ZmJiNDZiYzRjOWYxZTlkZDRlYWUyZGY0ZWFlNGY0MzQyNTc1NWUwOGYwZTgiLCJyb3V0ZXIiOiIvYXBpL3YxL3dlaWJvL3dlYl92Mi9mZXRjaF9wb3N0X2RldGFpbCIsInBhcmFtcyI6eyJpZCI6IjUzNTE3MjY4NjU0NDk5NjYiLCJpc19nZXRfbG9uZ190ZXh0IjoidHJ1ZSJ9LCJkYXRhIjp7InZpc2libGUiOnsidHlwZSI6MCwibGlzdF9pZCI6MH0sImNyZWF0ZWRfYXQiOiJUaHUgT2N0IDA4IDEyOjQyOjU4ICswODAwIDIwMjYiLCJpZCI6NTM1MTcyNjg2NTQ0OTk2NiwiaWRzdHIiOiI1MzUxNzI2ODY1NDQ5OTY2IiwibWlkIjoiNTM1MTcyNjg2NTQ0OTk2NiIsIm1ibG9naWQiOiJSbEhFcW1STUciLCJ1c2VyIjp7ImlkIjoyNDcxMzE3Nzg0LCJpZHN0ciI6IjI0NzEzMTc3ODQiLCJwY19uZXciOjcsInNjcmVlbl9uYW1lIjoi6LeR5q2l56m/6L+H6ZKf6byT5qW8IiwicHJvZmlsZV9pbWFnZV91cmwiOiJodHRwczovL3R2YXgyLnNpbmFpbWcuY24vY3JvcC4wLjAuMTAyNC4xMDI0LjUwLzkzNGQ1MTE4bHk4aWZiZWllMWswNmoyMHNnMHNnbjB3LmpwZz9LSUQ9aW1nYmVkLHR2YSZFeHBpcmVzPTE3OTE0NDk3OTAmc3NpZz1lciUyQkVvQVBHZDAiLCJwcm9maWxlX3VybCI6Ii91LzI0NzEzMTc3ODQiLCJ2ZXJpZmllZCI6ZmFsc2UsInZlcmlmaWVkX3R5cGUiOi0xLCJkb21haW4iOiIiLCJ3ZWloYW8iOiIiLCJzdGF0dXNfdG90YWxfY291bnRlciI6eyJ0b3RhbF9jbnRfZm9ybWF0IjoxODM4LCJjb21tZW50X2NudCI6IjU5MCIsInJlcG9zdF9jbnQiOiIzOTIiLCJsaWtlX2NudCI6Ijg1NiIsInRvdGFsX2NudCI6IjEsODM4In0sImF2YXRhcl9sYXJnZSI6Imh0dHBzOi8vdHZheDIuc2luYWltZy5jbi9jcm9wLjAuMC4xMDI0LjEwMjQuMTgwLzkzNGQ1MTE4bHk4aWZiZWllMWswNmoyMHNnMHNnbjB3LmpwZz9LSUQ9aW1nYmVkLHR2YSZFeHBpcmVzPTE3OTE0NDk3OTAmc3NpZz10MW1TOVl0MmVvIiwiYXZhdGFyX2hkIjoiaHR0cHM6Ly90dmF4Mi5zaW5haW1nLmNuL2Nyb3AuMC4wLjEwMjQuMTAyNC4xMDI0LzkzNGQ1MTE4bHk4aWZiZWllMWswNmoyMHNnMHNnbjB3LmpwZz9LSUQ9aW1nYmVkLHR2YSZFeHBpcmVzPTE3OTE0NDk3OTAmc3NpZz1XM25FcmpCaDMyIiwiZm9sbG93X21lIjpmYWxzZSwiZm9sbG93aW5nIjpmYWxzZSwibWJyYW5rIjozLCJtYnR5cGUiOjExLCJ2X3BsdXMiOjAsInVzZXJfYWJpbGl0eSI6MzQwNzg4MCwicGxhbmV0X3ZpZGVvIjpmYWxzZSwiaWNvbl9saXN0IjpbeyJ0eXBlIjoidmlwIiwiZGF0YSI6eyJtYnJhbmsiOjMsIm1idHlwZSI6MTEsInN2aXAiOjEsInZ2aXAiOjB9fV19LCJjYW5fZWRpdCI6ZmFsc2UsInRleHRMZW5ndGgiOjgwMywiYW5ub3RhdGlvbnMiOlt7InNwb3RfdHlwZSI6IjAifSx7InNob290aW5nIjoxLCJwbGFjZSI6eyJwb2lpZCI6IjgwMDg2NjEwMTAwMDAwMDAwMDAiLCJ0aXRsZSI6Iuilv+WuiSIsInR5cGUiOiJjaGVja2luIiwic3BvdF90eXBlIjoiMCJ9LCJjbGllbnRfbWJsb2dpZCI6ImlQaG9uZS1FRUQ2NzRFQy1EMjc5LTQxMUYtOUQ5RS00Q0Q0OTFDNzFBRDIifSx7InNvdXJjZV90ZXh0IjoiIiwicGhvbmVfaWQiOiIifSx7Im1hcGlfcmVxdWVzdCI6dHJ1ZX1dLCJzb3VyY2UiOiJpUGhvbmUgMTciLCJmYXZvcml0ZWQiOmZhbHNlLCJyaWQiOiIwXzBfMF80ODY3ODU0MTgwMjY4NDExMjU3XzBfMF8wIiwiZ2VvIjp7InR5cGUiOiJQb2ludCIsImNvb3JkaW5hdGVzIjpbMzQuMjYzMTYxLDEwOC45NDgwMjRdLCJkZXRhaWwiOnsicG9paWQiOiI4MDA4NjYxMDEwMDAwMDAwMDAwIiwidGl0bGUiOiLopb/lrokiLCJ0eXBlIjoiY2hlY2tpbiIsInNwb3RfdHlwZSI6IjAifX0sInBpY19udW0iOjAsImlzX3BhaWQiOmZhbHNlLCJtYmxvZ192aXBfdHlwZSI6MCwibnVtYmVyX2Rpc3BsYXlfc3RyYXRlZ3kiOnsiYXBwbHlfc2NlbmFyaW9fZmxhZyI6NTEsImRpc3BsYXlfdGV4dF9taW5fbnVtYmVyIjoxMDAwMDAwLCJkaXNwbGF5X3RleHQiOiIxMDDkuIcrIn0sInJlcG9zdHNfY291bnQiOjAsImNvbW1lbnRzX2NvdW50IjowLCJhdHRpdHVkZXNfY291bnQiOjIsImF0dGl0dWRlc19zdGF0dXMiOjAsImNvbnRpbnVlX3RhZyI6eyJ0aXRsZSI6IuWFqOaWhyIsInBpYyI6Imh0dHA6Ly9oNS5zaW5haW1nLmNuL3VwbG9hZC8yMDE1LzA5LzI1LzMvdGltZWxpbmVfY2FyZF9zbWFsbF9hcnRpY2xlLnBuZyIsInNjaGVtZSI6InNpbmF3ZWlibzovL2RldGFpbD9tYmxvZ2lkPTUzNTE3MjY4NjU0NDk5NjYmaWQ9NTM1MTcyNjg2NTQ0OTk2NiZuZXh0X2ZpZD0yMzI1MzJfbWJsb2cmZmVlZF9kZXRhaWxfdHlwZT0wIn0sImlzTG9uZ1RleHQiOnRydWUsImxvbmdUZXh0Ijp7ImNyZWF0ZWRfYXQiOiJUaHUgT2N0IDA4IDEyOjQyOjU4ICswODAwIDIwMjYiLCJhcHBpZCI6MjgzMDYwNiwiYW5ub3RhdGlvbnMiOlt7InNwb3RfdHlwZSI6IjAifSx7InNob290aW5nIjoxLCJwbGFjZSI6eyJwb2lpZCI6IjgwMDg2NjEwMTAwMDAwMDAwMDAiLCJ0aXRsZSI6Iuilv+WuiSIsInR5cGUiOiJjaGVja2luIiwic3BvdF90eXBlIjoiMCJ9LCJjbGllbnRfbWJsb2dpZCI6ImlQaG9uZS1FRUQ2NzRFQy1EMjc5LTQxMUYtOUQ5RS00Q0Q0OTFDNzFBRDIifSx7InNvdXJjZV90ZXh0IjoiIiwicGhvbmVfaWQiOiIifSx7Im1hcGlfcmVxdWVzdCI6dHJ1ZX1dLCJtYmxvZ192aXBfdHlwZSI6MCwidXNlciI6eyJpZCI6MjQ3MTMxNzc4NCwiaWRzdHIiOiIyNDcxMzE3Nzg0IiwiY2xhc3MiOjEsInNjcmVlbl9uYW1lIjoi6LeR5q2l56m/6L+H6ZKf6byT5qW8IiwibmFtZSI6Iui3keatpeepv+i/h+mSn+m8k+alvCIsInByb3ZpbmNlIjoiNjEiLCJjaXR5IjoiMSIsImxvY2F0aW9uIjoi6ZmV6KW/IOilv+WuiSIsImRlc2NyaXB0aW9uIjoi5oiR55m+5peg6IGK6LWW77yM5oiR5bCx6LeR5q2l77yM56m/6L+H77yM6ZKf6byT5qW8IiwidXJsIjoiIiwicHJvZmlsZV9pbWFnZV91cmwiOiJodHRwczovL3R2YXgyLnNpbmFpbWcuY24vY3JvcC4wLjAuMTAyNC4xMDI0LjUwLzkzNGQ1MTE4bHk4aWZiZWllMWswNmoyMHNnMHNnbjB3LmpwZz9LSUQ9aW1nYmVkLHR2YSZFeHBpcmVzPTE3OTE0NDk3OTAmc3NpZz1lciUyQkVvQVBHZDAiLCJsaWdodF9yaW5nIjpmYWxzZSwicHJvZmlsZV91cmwiOiJ1LzI0NzEzMTc3ODQiLCJkb21haW4iOiIiLCJ3ZWloYW8iOiIiLCJnZW5kZXIiOiJtIiwiZm9sbG93ZXJzX2NvdW50IjoxNTYzLCJmb2xsb3dlcnNfY291bnRfc3RyIjoiMTU2MyIsImZyaWVuZHNfY291bnQiOjEyOSwicGFnZWZyaWVuZHNfY291bnQiOjE5LCJzdGF0dXNlc19jb3VudCI6ODM1LCJ2aWRlb19zdGF0dXNfY291bnQiOjM3LCJ2aWRlb19wbGF5X2NvdW50IjowLCJzdXBlcl90b3BpY19ub3Rfc3luX2NvdW50IjowLCJmYXZvdXJpdGVzX2NvdW50IjoxNTAsImNyZWF0ZWRfYXQiOiJTdW4gT2N0IDE2IDEyOjI3OjQyICswODAwIDIwMTEiLCJmb2xsb3dpbmciOmZhbHNlLCJhbGxvd19hbGxfYWN0X21zZyI6ZmFsc2UsImdlb19lbmFibGVkIjpmYWxzZSwidmVyaWZpZWQiOmZhbHNlLCJ2ZXJpZmllZF90eXBlIjotMSwicmVtYXJrIjoiIiwiaW5zZWN1cml0eSI6eyJzZXh1YWxfY29udGVudCI6ZmFsc2V9LCJwdHlwZSI6MCwiYWxsb3dfYWxsX2NvbW1lbnQiOnRydWUsImF2YXRhcl9sYXJnZSI6Imh0dHBzOi8vdHZheDIuc2luYWltZy5jbi9jcm9wLjAuMC4xMDI0LjEwMjQuMTgwLzkzNGQ1MTE4bHk4aWZiZWllMWswNmoyMHNnMHNnbjB3LmpwZz9LSUQ9aW1nYmVkLHR2YSZFeHBpcmVzPTE3OTE0NDk3OTAmc3NpZz10MW1TOVl0MmVvIiwiYXZhdGFyX2hkIjoiaHR0cHM6Ly90dmF4Mi5zaW5haW1nLmNuL2Nyb3AuMC4wLjEwMjQuMTAyNC4xMDI0LzkzNGQ1MTE4bHk4aWZiZWllMWswNmoyMHNnMHNnbjB3LmpwZz9LSUQ9aW1nYmVkLHR2YSZFeHBpcmVzPTE3OTE0NDk3OTAmc3NpZz1XM25FcmpCaDMyIiwidmVyaWZpZWRfcmVhc29uIjoiIiwidmVyaWZpZWRfdHJhZGUiOiIiLCJ2ZXJpZmllZF9yZWFzb25fdXJsIjoiIiwidmVyaWZpZWRfc291cmNlIjoiIiwidmVyaWZpZWRfc291cmNlX3VybCI6IiIsImZvbGxvd19tZSI6ZmFsc2UsImxpa2UiOmZhbHNlLCJsaWtlX21lIjpmYWxzZSwib25saW5lX3N0YXR1cyI6MCwiYmlfZm9sbG93ZXJzX2NvdW50IjoxNywibGFuZyI6InpoLWNuIiwic3RhciI6MCwibWJ0eXBlIjoxMSwibWJyYW5rIjozLCJzdmlwIjoxLCJ2dmlwIjowLCJiYXNpY19tZW1iZXIiOjAsIm1iX2V4cGlyZV90aW1lIjoxODAwMjAxNjAwLCJibG9ja193b3JkIjowLCJibG9ja19hcHAiOjEsImxldmVsIjoxLCJ0eXBlIjoxLCJ1bGV2ZWwiOjAsInVzZXJfbGltaXQiOjAsImJhZGdlIjp7InVjX2RvbWFpbiI6MCwiZW50ZXJwcmlzZSI6MCwiYW5uaXZlcnNhcnkiOjAsInRhb2JhbyI6MCwiZ29uZ3lpIjowLCJnb25neWlfbGV2ZWwiOjAsImJpbmRfdGFvYmFvIjoxLCJkYWlsdiI6MCwiem9uZ3lpamkiOjAsInZpcF9hY3Rpdml0eTEiOjAsInVucmVhZF9wb29sIjoxLCJkYWl5YW4iOjAsInZpcF9hY3Rpdml0eTIiOjAsImZvb2xzX2RheV8yMDE2IjowLCJ1ZWZhX2V1cm9fMjAxNiI6MCwidW5yZWFkX3Bvb2xfZXh0IjoxLCJzZWxmX21lZGlhIjowLCJkendicWx4XzIwMTYiOjAsImRpc2NvdW50XzIwMTYiOjAsImZvbGxvd193aGl0ZWxpc3RfdmlkZW8iOjAsImxlYWd1ZV9iYWRnZSI6MCwibG9sX21zaV8yMDE3IjowLCJzdXBlcl9zdGFyXzIwMTciOjAsInZpZGVvX2F0dGVudGlvbiI6MCwidHJhdmVsXzIwMTciOjAsImxvbF9nbV8yMDE3IjowLCJjel93ZWRfMjAxNyI6MCwiaW5zcGVjdG9yIjowLCJwYW5kYSI6MCwidXZlX2ljb24iOjAsInVzZXJfbmFtZV9jZXJ0aWZpY2F0ZSI6MSwic3Vpc2hvdXBhaV8yMDE4IjowLCJ3ZW5kYSI6MCwid2VuY2h1YW5fMTB0aCI6MCwic3VwZXJfc3Rhcl8yMDE4IjowLCJ3b3JsZGN1cF8yMDE4IjowLCJ3ZW5kYV92MiI6MCwibGVhZ3VlX2JhZGdlXzIwMTgiOjAsImRhaWx2XzIwMTgiOjAsImFzaWFkXzIwMTgiOjAsInFpeGlfMjAxOCI6MCwieWlxaWp1YW5fMjAxOCI6MCwibWVpbGl6aG9uZ2d1b18yMDE4IjowLCJsb2xfczgiOjAsImtwbF8yMDE4IjowLCJuYXRpb25hbF9kYXlfMjAxOCI6MCwiZG91YmxlMTFfMjAxOCI6MCwid2VpYm9fZGlzcGxheV9mYW5zIjowLCJyZWxhdGlvbl9kaXNwbGF5IjowLCJ3Ynp5XzIwMTgiOjAsIm1lbW9yaWFsXzIwMTgiOjAsInZfaW5mbHVlbmNlXzIwMTgiOjAsImhvbmdiYW9mZWlfMjAxOSI6MCwic3RhdHVzX3Zpc2libGUiOjAsImRlbmdsb25nXzIwMTkiOjAsImZ1XzIwMTkiOjAsIndvbWVuc2RheV8yMDE4IjowLCJhdmVuZ2Vyc18yMDE5IjowLCJzdWlzaG91cGFpXzIwMTkiOjAsInd1c2lfMjAxOSI6MCwiZWFydGhfMjAxOSI6MCwiaG9uZ3JlbmppZV8yMDE5IjowLCJkYWlsdl8yMDE5IjowLCJjaGluYV8yMDE5IjowLCJob25na29uZ18yMDE5IjowLCJqdmh1YXN1YW5fMjAxOSI6MCwidGFvaHVheXVhbl8yMDE5IjowLCJkendicWx4XzIwMTkiOjAsInJyZ3lqXzIwMTkiOjAsImNpc2hhbl8yMDE5IjowLCJmYW1pbHlfMjAxOSI6MCwic2hvdWh1YW5fMjAxOSI6MCwiYW50XzIwMTkiOjAsIndlaXNoaV8yMDE5IjowLCJzaHVhbmcxMV8yMDE5IjowLCJrZHhfMjAxOSI6MCwid2J6eV8yMDE5IjowLCJzdGFybGlnaHRfMjAxOSI6MCwiZGFxaV8yMDE5IjowLCJnb25namlyaV8yMDE5IjowLCJtYWNhb18yMDE5IjowLCJjaGluYV8yMDE5XzIiOjAsImhvbmdiYW9fMjAyMCI6MCwiZmVpeWFuXzIwMjAiOjAsImhvcGVfMjAyMCI6MCwia2FuZ3lpXzIwMjAiOjAsImRha2FfMjAyMCI6MCwiZ3JlZW5fMjAyMCI6MCwiZ3JhZHVhdGlvbl8yMDIwIjowLCJwY19uZXciOjcsImtmY18yMDIwIjowLCJkYWlsdl8yMDIwIjowLCJtb3ZpZV8yMDIwIjowLCJtaV8yMDIwIjowLCJ2cGlja18yMDIwIjowLCJjZGR5aF8yMDIwIjowLCJuaWtlXzIwMjAiOjAsInNjaG9vbF8yMDIwIjowLCJnb25neWlfMjAyMCI6MCwiaG9uZ3JlbmppZV8yMDIwIjowLCJ0ZXN0X2ljb24iOjAsImNoaW5hXzIwMjAiOjAsIm5pc3Nhbl8yMDIwIjowLCJ6anN6Z2ZfMjAyMCI6MCwiemFvbGFuZ18yMDIwIjowLCJhaXppXzIwMjAiOjAsIndlbm51YW5qaV8yMDIwIjowLCJ3ZWlib3poaXllXzIwMjAiOjAsInlpamlhN18yMDIwIjowLCJrZmNmbGFnXzIwMjEiOjAsImhvbmdiYW9mZWlmdW5pdV8yMDIxIjowLCJjdWNjaWRsYW0yMF8yMDIxIjowLCJjdWNjaWRsYW0xMl8yMDIxIjowLCJjdWNjaWRsYW0yNV8yMDIxIjowLCJob25nYmFvZmVpamlrYV8yMDIxIjowLCJzaGVxdXdlaXl1YW5fMjAyMSI6MCwid2VpYm96aGl5ZXhpYW54aWFfMjAyMSI6MCwiemhvbmdjYW9ndWFuXzIwMjEiOjAsIm5paGFvc2hlbmdodW9qaWVfMjAyMSI6MCwibHZ6aGlsaW5neWFuZ18yMDIxIjowLCJ4aWFvbWluZXdsb2dvXzIwMjEiOjAsImRpc25leTVfMjAyMSI6MCwiZWFydGhndWFyZGVyXzIwMjEiOjAsInl1YW5sb25ncGluZ18yMDIxIjowLCJ5bHBzaHVpZGFvXzIwMjEiOjAsImJyYW5kX2FjY291bnRfMjAyMSI6MCwiZ2Fva2FvXzIwMjEiOjEsIm91emhvdWJlaV8yMDIxIjowLCJiaXllamlfMjAyMSI6MCwicGFydHlfY2FyZGlkX3N0YXRlIjowLCJob25ncmVuamllXzIwMjEiOjAsImFveXVuXzIwMjEiOjAsInpob25nY2FvdXNlcl8yMDIxIjowLCJkYWlsdV8yMDIxIjowLCJjb21wYW5pb25fY2FyZCI6MCwiZmlzaGZhcm1fMjAyMSI6MCwia2FpeHVlMjFfMjAyMSI6MCwiemhvbmdodWFjaXNoYW5yaV8yMDIxIjowLCJyZW5yZW5nb25neWlqaWVfMjAyMSI6MCwieWlueXVlamllMjFfMjAyMSI6MCwicWlhbmJhb2Z1XzIwMjEiOjAsInlpbmd4aW9uZ2xpYW5tZW5nczExXzIwMjEiOjAsInl4bG1scGxfMjAyMSI6MCwiaG9uZ2Jhb2ZlaV8yMDIyIjowLCJxaWNoZW5xaWNoZV8yMDIxIjowLCJ3ZWlib3poaXllXzIwMjEiOjAsIndlaWJvemhpeWVib2Jhb18yMDIxIjowLCJzb2NpYWxfY29udGVudCI6MCwiaG9uZ2Jhb2ZlaTIwMjJfMjAyMSI6MCwiZG9uZ2FvaHVpXzIwMjIiOjAsInBjX2V4cGVyaW1lbnQiOjAsInlvdXlpY18yMDIyIjowLCJuZXdkb25nYW9odWlfMjAyMiI6MCwiYmRkeHJyZG9uZ2FvaHVpXzIwMjIiOjAsImx2emhpbGluZ3lhbmdfMjAyMiI6MCwid2VubWluZ3hpYW9iaWFvYmluZ18yMDIyIjowLCJuaWhhb2NodW50aWFuXzIwMjIiOjAsInZpZGVvX3Zpc2libGUiOjAsImNlc2hpaWNvbl8yMDIyIjowLCJ6dWltZWlsYW9kb25namllXzIwMjIiOjAsImlwbG9jYXRpb25jaGFuZ2VfMjAyMiI6MCwiYml5ZWppXzIwMjIiOjAsInNodWlkYW9fMjAyMiI6MCwibWVuZ25pdV8yMDIyIjowLCJpc191bml2ZXJzaXR5IjowLCJjaXR5X3VuaXZlcnNpdHkiOjAsImdhb2thb18yMDIyIjowLCJxdWFubWluamlhbnNoZW5fMjAyMiI6MCwiaGFuZ211XzIwMjIiOjAsImd1b3FpXzIwMjIiOjAsImdhbmdxaV8yMDIyIjowLCJkYWlsdl8yMDIyIjowLCJkYWlsdm1pbmd4aW5nXzIwMjIiOjAsImNvbW1lbnRfc291cmNlIjowLCJodW9iYW5fMjAyMiI6MCwiemhvbmdxaXVqaWVfMjAyMiI6MCwia2FpeHVlamlfMjAyMiI6MCwicmVucmVuZ29uZ3lpamllXzIwMjIiOjAsImd1b3FpbmdfMjAyMiI6MCwiZ3VvcV8yMDIyIjowLCJzMTJfMjAyMiI6MCwiY2xvY2tfaW5fdWciOjAsImhvbmdyZW5qaWVfMjAyMiI6MCwicGlqaW5nemhhbmppXzIwMjIiOjAsImd1YW5ncGFueGluZ2RvbmdfMjAyMiI6MCwic2hpamllYmVpXzIwMjIiOjAsImhvbmdyZW5qaWVuZXdfMjAyMiI6MCwic2hpamllYmVpZ29sZGVuXzIwMjIiOjAsImJhb2tlbWVuZ18yMDIyIjowLCJtb3l1ZGFrYV8yMDIyIjowLCJqaWFuY2ppeXVuZG9uZ18yMDIyIjowLCJ6aHVpanVkYWthXzIwMjIiOjAsInNoZW55ZXNodWRvbmdkYWthXzIwMjIiOjAsInN1aXNob3VwYWlkYWthXzIwMjIiOjAsIm1laXJpbWVuZ2Nob25nZGFrYV8yMDIyIjowLCJtZWlyaXphb3FpZGFrYV8yMDIyIjowLCJtZWlyaXlpY2FuZGFrYV8yMDIyIjowLCJyYW5naG9uZ2Jhb2ZlaV8yMDIzIjowLCJwaW5nYW5ndW9fMjAyMiI6MCwieXVhbnNoZW5fMjAyMyI6MCwiY2h1bmppZXNoZXlpbmdkYXNhaV8yMDIzIjowLCJ0dW5pYW5kaXlpdGlhb3dlaWJvXzIwMjMiOjAsInhpbnl1bmNhb18yMDIzIjowLCJ0YW9odWFfMjAyMyI6MCwic2hhbmd5ZWNlc2hpMSI6MCwic2hhbmd5ZWNlc2hpMiI6MCwic2hhbmd5ZWNlc2hpMyI6MCwic2h1aW1pYW5yaV8yMDIzIjowLCJkaXFpdXlpeGlhb3NoaV8yMDIzIjowLCJzdGFyX2Nyb3duIjowLCJndWFuZ3l1eWV4aW5nXzIwMjMiOjAsInlheWFfcGFuZGEiOjAsIndlaXhpYW9yaV8yMDIzIjowLCJtdXFpbmppZV8yMDIzIjowLCJkdW1laV8yMDIyIjowLCJiaXllamlfMjAyMyI6MCwiZ2Fva2FvXzIwMjMiOjAsImR1YW53dWppZV8yMDIzIjowLCJ4dWV4aWRha2FfMjAyMyI6MCwiaGFvd3VmZW54aWFuZ2Rha2FfMjAyMyI6MCwiemh1aWZhbmRha2FfMjAyMyI6MCwibnZ6dV8yMDIzIjowLCJndWFuZ3l1eWVfMjAyMyI6MCwidGZib3lfMjAyMyI6MCwid2VpbGFuZGFuZ2FuXzIwMjMiOjAsInFpeGlfMjAyMyI6MCwiZ3Vhbmd5dXllemhpbGlhbl8yMDIzIjowLCJyZW5yZW5nb25neWlqaWVfMjAyMyI6MCwia2FpeHVlamlfMjAyMyI6MCwieWF5dW5odWlfMjAyMyI6MCwieWF5dW5odWlfZGlhbmppbmciOjAsImxhb3NoaXlleWVuaV8yMDIzIjowLCJ5YXl1bmh1aWd1b3FpXzIwMjMiOjAsImd1YW5nbWluZ3l1ZW1hbl8yMDIzIjowLCJzMTNfMjAyMyI6MCwid2FuZ3poZXJvbmd5YW9fMjkyMyI6MCwidXNlcl9pZGVudGl0eV9hdXRoIjoxLCJiYXdhbmdjaGFqaV8yMDIzIjowLCJndWFuZ3poaXllXzIwMjMiOjAsInVzZXJfcmVhbGl0eV9hdXRoIjowLCJnYW9rYW9qaWF5b3VfMjAyMyI6MCwiYmFva2VtZW5nXzIwMjMiOjAsImhhaW1pYW5iYW9iYW9ndW9zaGVuZ2Rhbl8yMDIzIjowLCJ4dWdleGluZ3l1YW5fMjAyMyI6MCwiZmVuZGlfMjAyMyI6MCwibGlhbnl1c2hlbmcxXzIwMjQiOjAsImxpYW55dXNoZW5nMl8yMDI0IjowLCJsaWFueXVzaGVuZzNfMjAyNCI6MCwiZ3Vhbmd5dXllemhpbGlhbl8yMDI0IjowLCJhcnRpY2xlX3Zpc2libGUiOjAsImdhbm1hb2xpbmdfMjAyNCI6MCwieXVhbm1lbmd6aGl4aW5nXzIwMjQiOjAsIm5paGFvY2h1bnRpYW5fMjAyNCI6MCwibHZ6aGlsaW5neWFuZ18yMDI0IjowLCJzdGF0dXNfdmlzaWJsZV95IjowLCJoYW5nbXVfMjAyNCI6MCwiZ3Vhbmd5dXllXzIwMjQiOjAsImdhb2thb18yMDI0IjowLCJiaXllamlfMjAyNCI6MCwic3FqbmhkaWFuc2hpXzIwMjQiOjAsInB1cmNoYXNlZF9wYWlkX2NvbnRlbnQiOjAsImNoYW5neGlhbmdzaV8yMDI0IjowLCJ6aHVhbWFvbWFvXzIwMjQiOjAsImFveXVuXzIwMjQiOjAsInhpYXJpcWluZ2NodW5wYWlkdWlfMjAyNCI6MCwicmVucmVuZ29uZ3lpamllXzIwMjQiOjAsImthaXh1ZWppXzIwMjQiOjAsImppYW9zaGlqaWVfMjAyNCI6MCwiemhvbmdxaXVfMjAyNCI6MCwicnV5dWFuXzIwMjQiOjAsImd1b3FpMTAwMV8yMDI0IjowLCJoZXBpbmdqaW5neWluZ18yMDI0IjowLCJhY2dfMjAyNCI6MCwiYmF3YW5nY2hhamlfMjAyNCI6MCwidHlteWRfMjAyNCI6MCwibXJ4eV8yMDI0IjowLCJocnNqXzIwMjUiOjAsImt4bl8yMDI1IjowLCJjd18yMDI1IjowLCJsemx5XzIwMjUiOjAsImx1aGFuenFfMjAyNSI6MCwibXVxaW5qaWVfMjAyNSI6MCwiZHVvaGFzaGliaW5fMjAyNSI6MCwiZ2Fva2FvXzIwMjUiOjAsImtlbmFuXzIwMjUiOjAsImJpeWVqaV8yMDI1IjowLCJocGdfMjAyNSI6MCwia3hqXzIwMjUiOjAsImpzal8yMDI1IjowLCJndW9xaW5nXzIwMjUiOjAsImRhb2h1aV8yMDI2IjowLCJ5dWFuYmFvXzIwMjYiOjAsImZ1XzIwMjYiOjAsImx6bHlfMjAyNiI6MCwiYmFvc2hpbG9uZ18xIjowLCJzeV9semx5dGVzdF8yMDI2IjowLCJsemx5MDVfMjAyNiI6MCwic3lfc2piXzIwMjYiOjAsInlqZGtfMjAyNiI6MCwia2VuYW5fMjAyNiI6MCwic3VwZXJfdG9waWNfcGx1cyI6MCwia2FpeHVlamlfMjAyNiI6MCwianNqXzIwMjYiOjAsInpxal8yMDI2IjowfSwiYmFkZ2VfdG9wIjoiIiwiaGFzX2FiaWxpdHlfdGFnIjoxLCJleHRlbmQiOnsicHJpdmFjeSI6eyJtb2JpbGUiOjAsImltZ19zZWFyY2hfZGlzYWJsZWQiOjB9LCJtYnByaXZpbGVnZSI6IjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDRjMDAyMDgifSwiY2hhb2h1YV9hYmlsaXR5IjowLCJicmFuZF9hYmlsaXR5IjowLCJuZnRfYWJpbGl0eSI6MCwidnBsdXNfYWJpbGl0eSI6MCwid2VuZGFfYWJpbGl0eSI6MCwibGl2ZV9hYmlsaXR5IjowLCJnb25neWlfYWJpbGl0eSI6MCwicGF5Y29sdW1uX2FiaWxpdHkiOjAsIm5ld2JyYW5kX2FiaWxpdHkiOjAsImVjb21tZXJjZV9hYmlsaXR5IjowLCJoYXJkZmFuX2FiaWxpdHkiOjEsIndiY29sdW1uX2FiaWxpdHkiOjAsImludGVyYWN0aW9uX3VzZXIiOjAsImF1ZGlvX2FiaWxpdHkiOjAsInBsYWNlX2FiaWxpdHkiOjEsImJsdWV2X2FkX2FiaWxpdHkiOjAsImFiaWxpdHlfdGFncyI6IuiusOiAhSIsImNyZWRpdF9zY29yZSI6ODAsInVzZXJfYWJpbGl0eSI6MzQwNzg4MCwidXJhbmsiOjI0LCJzdG9yeV9yZWFkX3N0YXRlIjotMSwic3RvcnlfaWQiOiIyNDcxMzE3Nzg0XzAiLCJzdG9yeV9zY2hlbWUiOiJzaW5hd2VpYm86Ly9zdG9yeS9zZWdtZW50P3R5cGU9MSZzdG9yeV9pZD0yNDcxMzE3Nzg0XzAmc2VnbWVudF9pZD0wIiwidmNsdWJfbWVtYmVyIjowLCJpc190ZWVuYWdlciI6MCwiaXNfZ3VhcmRpYW4iOjAsImlzX3RlZW5hZ2VyX2xpc3QiOjAsInBjX25ldyI6Nywic3BlY2lhbF9mb2xsb3ciOmZhbHNlLCJwbGFuZXRfdmlkZW8iOjIsInZpZGVvX21hcmsiOjAsImxpdmVfc3RhdHVzIjowLCJ1c2VyX2FiaWxpdHlfZXh0ZW5kIjo2Niwic3RhdHVzX3RvdGFsX2NvdW50ZXIiOnsidG90YWxfY250IjoxODM4LCJyZXBvc3RfY250IjozOTIsImNvbW1lbnRfY250Ijo1OTAsImxpa2VfY250Ijo4NDksImNvbW1lbnRfbGlrZV9jbnQiOjd9LCJ2aWRlb190b3RhbF9jb3VudGVyIjp7InBsYXlfY250IjoyNDUxN30sImJyYW5kX2FjY291bnQiOjAsImhvbmdiYW9mZWkiOjAsInRhYl9tYW5hZ2UiOiJbMCwgMF0iLCJyZXdhcmRfc3RhdHVzIjowLCJncmVlbl9tb2RlIjowLCJncmVlbl9tb2RlX3NvdXJjZSI6MCwiZGVsZXRlX21vZGVfdGltZSI6MCwidXJpc2siOjg3OTYwOTMwMjIyMDgsInVuZm9sbG93aW5nX3JlY29tX3N3aXRjaCI6MSwiYXZhdGFyX3R5cGUiOjAsImlzX2JpZyI6MCwiYXV0aF9zdGF0dXMiOjEsImF1dGhfcmVhbG5hbWUiOm51bGwsImF1dGhfY2FyZWVyIjpudWxsLCJhdXRoX2NhcmVlcl9uYW1lIjpudWxsLCJzaG93X2F1dGgiOjAsImlzX2F1dGgiOjAsImlzX3B1bmlzaCI6MCwiYXZhdGFyX2hkX3BpZCI6IjkzNGQ1MTE4bHk4aWZiZWllMWswNmoyMHNnMHNnbjB3IiwibGlrZV9kaXNwbGF5IjowLCJjb21tZW50X2Rpc3BsYXkiOjB9LCJ3ZWlib19wb3NpdGlvbiI6MSwic2hvd19hdHRpdHVkZV9iYXIiOjAsInRhZ19zdHJ1Y3QiOlt7InRhZ19uYW1lIjoi6KW/5a6JIiwidGFnX3NjaGVtZSI6InNpbmF3ZWlibzovL3BhZ2VpbmZvP2NvbnRhaW5lcmlkPTEwMDgwODc5YjIxMDQ0ZDA0NGM1ZmRjZjUyZGIyZDIyZDczZmI3Xy1fbGJzJmxjYXJkaWQ9ZnJvbXBvaSZleHRwYXJhbT1mcm9tcG9pIiwidXJsX3R5cGVfcGljIjoiaHR0cHM6Ly9oNS5zaW5haW1nLmNuL3VwbG9hZC8xMDAvOTcyLzIwMjIvMDYvMTMvdGltZWxpbmVfbG9jYXRpb24ucG5nIiwib2lkIjoiMTAyMjoxMDAxMDE4MDA4NjYxMDEwMDAwMDAwMDAwIiwib3R5cGUiOiJwbGFjZSIsInRhZ190eXBlIjoxLCJ0YWdfaGlkZGVuIjoyLCJvcmlfdXJsIjoiaHR0cDovL3QuY24vUjJXeGREWCIsImFjdGlvbmxvZyI6eyJhY3RfY29kZSI6MjQxMywib2lkIjoiMTAyMjoxMDAxMDE4MDA4NjYxMDEwMDAwMDAwMDAwIiwidWljb2RlIjpudWxsLCJsdWljb2RlIjpudWxsLCJmaWQiOm51bGwsImV4dCI6Im9yaWZpZDoifSwiZGVzYyI6Iueis+awtOe+jumjn+S5i+mDvSIsImlzX2NoZWNraW4iOjF9XSwidG9waWNfc3RydWN0IjpbeyJ0aXRsZSI6IiIsInRvcGljX3VybCI6InNpbmF3ZWlibzovL3NlYXJjaGFsbD9jb250YWluZXJpZD0yMzE1MjImcT0lMjMlRTUlQjAlOEElRTclOTUlOENWODAwJUU1JTg4JUI5JUU4JUJEJUE2JUU4JUI4JThGJUU2JTlEJUJGJUU2JTk0JUFGJUU2JTlFJUI2JUU2JTk2JUFEJUU4JUEzJTgyJTIzJmV4dHBhcmFtPSUyMyVFNSVCMCU4QSVFNyU5NSU4Q1Y4MDAlRTUlODglQjklRTglQkQlQTYlRTglQjglOEYlRTYlOUQlQkYlRTYlOTQlQUYlRTYlOUUlQjYlRTYlOTYlQUQlRTglQTMlODIlMjMiLCJ0b3BpY190aXRsZSI6IuWwiueVjFY4MDDliLnovabouI/mnb/mlK/mnrbmlq3oo4IiLCJhY3Rpb25sb2ciOnsiYWN0X3R5cGUiOjEsImFjdF9jb2RlIjozMDAsIm9pZCI6IjEwMjI6MjMxNTIyYmFmZDRmYjhkMTgzNjQ4ZGI0NjJlNTAyODYyMDFkNTciLCJ1dWlkIjo1MzUxNjQwODE0NTg0Mjk3LCJjYXJkaWQiOiIiLCJsY2FyZGlkIjoiIiwidWljb2RlIjoiIiwibHVpY29kZSI6IiIsImZpZCI6IiIsImxmaWQiOiIiLCJleHQiOiJtaWQ6NTM1MTcyNjg2NTQ0OTk2NnxyaWQ6fHNob3J0X3VybDp8bG9uZ191cmw6fGNvbW1lbnRfaWQ6fG1pZHVpZDoyNDcxMzE3Nzg0fHJvb3RtaWQ6NTM1MTcyNjg2NTQ0OTk2Nnxyb290dWlkOjI0NzEzMTc3ODR8YXV0aG9yaWQ6fHV1aWQ6NTM1MTY0MDgxNDU4NDI5N3xpc19hZF93ZWlibzowfG9pZDoxMDIyOjIzMTUyMmJhZmQ0ZmI4ZDE4MzY0OGRiNDYyZTUwMjg2MjAxZDU3In19XSwiY29udGVudCI6IuWcqOWQjeWIqeWcuuS4reW/g++8jOaIkeS7rOS5oOaDr+S6hueci+i9puS8geeUqOKAnOWFqOmTvui3r+WGl+S9meKAneeahOWuj+Wkp+WPmeS6i+adpeWghuegjOWuieWFqOaEn++8jOWNtOW+iOWwkeWOu+WuoeinhumCo+S6m+e7tOaMgei/kOi9rOeahOacgOW6leWxgumAu+i+keOAglxuXG7lsIrnlYxWODAw5Zyo5oeC6L2m5bid55qE5rWL6K+V5Lit77yMM+WPsOaWsOi9puWcqDEwMGttL2jntKfmgKXliLbliqjml7bliLnovabouI/mnb/mlK/mnrblhajpg6jmlq3oo4LvvIzov5nnp43lnKjmnoHpmZDmi4nplK/kuIvnnqzpl7TltKnloYznmoTniannkIbnp6nluo/vvIzpgI/nnYDlr7nlt6XkuJrlupXnur/lpLHlrojnmoTorr3liLrjgILlvZPlrqPkvKDph4znmoTljY7kuLrpgJTngbXpvpnooYzlubPlj7Dov5jlnKjlvLrosIPmmbrpqb7kuI7kvpvnlLXns7vnu5/nmoTnsr7lr4bljY/kvZzml7bvvIzmnIDln7rnoYDnmoTkurrlipvmnLrmorDlhZzlupXpg6jku7bljbTlnKjov57nu63ph43liLnkuK3njoflhYjlpLHmlYjjgIJcblxu55yf5q2j55qE5a6J5YWo5a6a5Yqb5LiN5piv5Zyo6aG65aKD5Lit5Lqr5Y+X55S15a2Q6YWN572u55qE5aCG5paZ77yM6ICM5piv5Zyo6KeE5YiZ5Y+Y5Yqo5pe25L6d54S25pyJ5bqV5rCU5a6I5L2P5LiT5Lia55qE6L6555WM44CC6Z2i5a+55pat6KOC5ZCO5LuOMzjnsbPmmrTlop7oh7MxNDDnsbPnmoTliLbliqjot53nprvvvIzku6Xlj4rkvY7kuo7lm73moIcyMDAwTuimgeaxgueahDE2MTJO5Y+X5Yqb5pWw5o2u77yM6L+Z56eN5LiN5Li655+t5pyf5rWB6YeP5aal5Y2P55Sf5a2Y5bqV57q/55qE5YGa5rOV77yM5q+U5Lu75L2V57K+5L+u55qE5ruk6ZWc6YO95pu05pyJ6K+05pyN5Yqb44CCXG5cbuaEv+i/meS7vemch+WKqOiDveiuqeWQjuadpeiAheaYjueZve+8jOecn+ato+eahOmrmOe6p+aEn+S4jeaYr+mdoOWPo+WPt+eahOWWp+Wao+WghuegjO+8jOiAjOaYr+mdoOWvuemCo+S6m+e7j+W+l+i1t+aOqOaVsueahOe7huiKgueahOmpu+i2s+OAguWcqOS/oeaBr+eIhueCuOeahOW9k+S4i++8jOS+neeEtuacieS6uuaEv+aEj+S4uui/meenjeWcqOW6n+Win+S4iumHjeW7uuiHquaIkeenqeW6j+aEn+eahOS7o+S7t+S5sOWNleOAgiPlsIrnlYxWODAw5Yi56L2m6LiP5p2/5pSv5p625pat6KOCIyAifSwibWxldmVsIjowLCJjb250ZW50X2F1dGgiOjAsImlzX3Nob3dfYnVsbGV0aW4iOjIsImNvbW1lbnRfbWFuYWdlX2luZm8iOnsiY29tbWVudF9wZXJtaXNzaW9uX3R5cGUiOi0xLCJhcHByb3ZhbF9jb21tZW50X3R5cGUiOjAsImNvbW1lbnRfc29ydF90eXBlIjowLCJjb21tZW50X2Fub25fdHlwZSI6MH0sInNoYXJlX3JlcG9zdF90eXBlIjowLCJ0b3BpY19zdHJ1Y3QiOlt7InRpdGxlIjoiIiwidG9waWNfdXJsIjoic2luYXdlaWJvOi8vc2VhcmNoYWxsP2NvbnRhaW5lcmlkPTIzMTUyMiZxPSUyMyVFNSVCMCU4QSVFNyU5NSU4Q1Y4MDAlRTUlODglQjklRTglQkQlQTYlRTglQjglOEYlRTYlOUQlQkYlRTYlOTQlQUYlRTYlOUUlQjYlRTYlOTYlQUQlRTglQTMlODIlMjMmZXh0cGFyYW09JTIzJUU1JUIwJThBJUU3JTk1JThDVjgwMCVFNSU4OCVCOSVFOCVCRCVBNiVFOCVCOCU4RiVFNiU5RCVCRiVFNiU5NCVBRiVFNiU5RSVCNiVFNiU5NiVBRCVFOCVBMyU4MiUyMyIsInRvcGljX3RpdGxlIjoi5bCK55WMVjgwMOWIuei9pui4j+adv+aUr+aetuaWreijgiIsImFjdGlvbmxvZyI6eyJhY3RfdHlwZSI6MSwiYWN0X2NvZGUiOjMwMCwib2lkIjoiMTAyMjoyMzE1MjJiYWZkNGZiOGQxODM2NDhkYjQ2MmU1MDI4NjIwMWQ1NyIsInV1aWQiOjUzNTE2NDA4MTQ1ODQyOTcsImNhcmRpZCI6IiIsImxjYXJkaWQiOiIiLCJ1aWNvZGUiOiIiLCJsdWljb2RlIjoiIiwiZmlkIjoiIiwibGZpZCI6IiIsImV4dCI6Im1pZDo1MzUxNzI2ODY1NDQ5OTY2fHJpZDp8c2hvcnRfdXJsOnxsb25nX3VybDp8Y29tbWVudF9pZDp8bWlkdWlkOjI0NzEzMTc3ODR8cm9vdG1pZDo1MzUxNzI2ODY1NDQ5OTY2fHJvb3R1aWQ6MjQ3MTMxNzc4NHxhdXRob3JpZDp8dXVpZDo1MzUxNjQwODE0NTg0Mjk3fGlzX2FkX3dlaWJvOjB8b2lkOjEwMjI6MjMxNTIyYmFmZDRmYjhkMTgzNjQ4ZGI0NjJlNTAyODYyMDFkNTcifX1dLCJ0YWdfc3RydWN0IjpbeyJ0YWdfbmFtZSI6Iuilv+WuiSIsInRhZ19zY2hlbWUiOiJzaW5hd2VpYm86Ly9wYWdlaW5mbz9jb250YWluZXJpZD0xMDA4MDg3OWIyMTA0NGQwNDRjNWZkY2Y1MmRiMmQyMmQ3M2ZiN18tX2xicyZsY2FyZGlkPWZyb21wb2kmZXh0cGFyYW09ZnJvbXBvaSIsInVybF90eXBlX3BpYyI6Imh0dHBzOi8vaDUuc2luYWltZy5jbi91cGxvYWQvMTAwLzk3Mi8yMDIyLzA2LzEzL3RpbWVsaW5lX2xvY2F0aW9uLnBuZyIsIm9pZCI6IjEwMjI6MTAwMTAxODAwODY2MTAxMDAwMDAwMDAwMCIsIm90eXBlIjoicGxhY2UiLCJ0YWdfdHlwZSI6MSwidGFnX2hpZGRlbiI6Miwib3JpX3VybCI6Imh0dHA6Ly90LmNuL1IyV3hkRFgiLCJhY3Rpb25sb2ciOnsiYWN0X2NvZGUiOjI0MTMsIm9pZCI6IjEwMjI6MTAwMTAxODAwODY2MTAxMDAwMDAwMDAwMCIsInVpY29kZSI6bnVsbCwibHVpY29kZSI6bnVsbCwiZmlkIjpudWxsLCJleHQiOiJvcmlmaWQ6In0sImRlc2MiOiLnorPmsLTnvo7po5/kuYvpg70iLCJpc19jaGVja2luIjoxfV0sInRpdGxlIjp7InRleHQiOiLlhazlvIAiLCJiYXNlX2NvbG9yIjoxLCJpY29uX3VybCI6Imh0dHA6Ly9oNS5zaW5haW1nLmNuL3VwbG9hZC8yMDE1LzA3LzE0LzM0L3RpbWVsaW5lX3RpdGxlX3B1YmxpYy5wbmcifSwibWJsb2d0eXBlIjowLCJzaG93RmVlZFJlcG9zdCI6ZmFsc2UsInNob3dGZWVkQ29tbWVudCI6ZmFsc2UsInBpY3R1cmVWaWV3ZXJTaWduIjpmYWxzZSwic2hvd1BpY3R1cmVWaWV3ZXIiOmZhbHNlLCJyY0xpc3QiOltdLCJhbmFseXNpc19leHRyYSI6IiIsInJlYWR0aW1ldHlwZSI6Im1ibG9nIiwibWl4ZWRfY291bnQiOjAsImlzX3Nob3dfbWl4ZWQiOmZhbHNlLCJtYmxvZ19mZWVkX2JhY2tfbWVudXNfZm9ybWF0IjpbXSwiaXNBZCI6ZmFsc2UsImlzU2luZ2xlUGF5QXVkaW8iOmZhbHNlLCJtZF9yZW5kZXJfbWFyayI6bnVsbCwidGV4dCI6IuWcqOWQjeWIqeWcuuS4reW/g++8jOaIkeS7rOS5oOaDr+S6hueci+i9puS8geeUqOKAnOWFqOmTvui3r+WGl+S9meKAneeahOWuj+Wkp+WPmeS6i+adpeWghuegjOWuieWFqOaEn++8jOWNtOW+iOWwkeWOu+WuoeinhumCo+S6m+e7tOaMgei/kOi9rOeahOacgOW6leWxgumAu+i+keOAgjxiciAvPjxiciAvPuWwiueVjFY4MDDlnKjmh4LovabluJ3nmoTmtYvor5XkuK3vvIwz5Y+w5paw6L2m5ZyoMTAwa20vaOe0p+aApeWItuWKqOaXtuWIuei9pui4j+adv+aUr+aetuWFqOmDqOaWreijgu+8jOi/meenjeWcqOaegemZkOaLiemUr+S4i+eerOmXtOW0qeWhjOeahOeJqeeQhuenqeW6j++8jOmAj+edgOWvueW3peS4muW6lee6v+WkseWuiOeahOiuveWIuuOAguW9k+Wuo+S8oOmHjOeahOWNjuS4uumAlOeBtem+meihjOW5s+WPsOi/mOWcqOW8uuiwg+aZuumpvuS4juS+m+eUteezu+e7n+eahOeyvuWvhuWNj+S9nOaXtu+8jOacgOWfuuehgOeahOS6uuWKm+acuuaisOWFnOW6lemDqOS7tuWNtOWcqOi/nue7remHjeWIueS4reeOh+WFiOWkseaViOOAgjxiciAvPjxiciAvPuecn+ato+eahOWuieWFqOWumuWKm+S4jeaYr+WcqOmhuuWig+S4reS6q+WPl+eUteWtkOmFjee9rueahOWghuaWme+8jOiAjOaYr+WcqOinhOWImeWPmOWKqOaXtuS+neeEtuacieW6leawlOWuiOS9j+S4k+S4mueahOi+ueeVjOOAgumdouWvueaWreijguWQjuS7jjM457Gz5pq05aKe6IezMTQw57Gz55qE5Yi25Yqo6Led56a777yM5Lul5Y+K5L2O5LqO5Zu95qCHMjAwME7opoHmsYLnmoQxNjEyTuWPl+WKm+aVsOaNru+8jOi/meenjeS4jeS4uuefreacn+a1gemHj+WmpeWNj+eUn+WtmOW6lee6v+eahOWBmuazle+8jOavlOS7u+S9leeyvuS/rueahOa7pOmVnOmDveabtOacieivtOacjeWKm+OAgjxiciAvPjxiciAvPuaEv+i/meS7vemch+WKqOiDveiuqeWQjuadpeiAheaYjueZve+8jOecn+ato+eahOmrmOe6p+aEn+S4jeaYr+mdoOWPo+WPt+eahOWWp+Wao+WghuegjO+8jOiAjOaYr+mdoOWvuemCo+S6m+e7j+W+l+i1t+aOqOaVsueahOe7huiKgueahOmpu+i2s+OAguWcqOS/oeaBr+eIhueCuOeahOW9k+S4i++8jOS+neeEtuacieS6uuaEv+aEj+S4uui/meenjeWcqOW6n+Win+S4iumHjeW7uuiHquaIkeenqeW6j+aEn+eahOS7o+S7t+S5sOWNleOAgjxhIGhyZWY9XCIvL3Mud2VpYm8uY29tL3dlaWJvP3E9JTIzJUU1JUIwJThBJUU3JTk1JThDVjgwMCVFNSU4OCVCOSVFOCVCRCVBNiVFOCVCOCU4RiVFNiU5RCVCRiVFNiU5NCVBRiVFNiU5RSVCNiVFNiU5NiVBRCVFOCVBMyU4MiUyM1wiIHRhcmdldD1cIl9ibGFua1wiPiPlsIrnlYxWODAw5Yi56L2m6LiP5p2/5pSv5p625pat6KOCIzwvYT4gIiwidGV4dF9yYXciOiLlnKjlkI3liKnlnLrkuK3lv4PvvIzmiJHku6zkuaDmg6/kuobnnIvovabkvIHnlKjigJzlhajpk77ot6/lhpfkvZnigJ3nmoTlro/lpKflj5nkuovmnaXloIbnoIzlronlhajmhJ/vvIzljbTlvojlsJHljrvlrqHop4bpgqPkupvnu7TmjIHov5DovaznmoTmnIDlupXlsYLpgLvovpHjgIJcblxu5bCK55WMVjgwMOWcqOaHgui9puW4neeahOa1i+ivleS4re+8jDPlj7DmlrDovablnKgxMDBrbS9o57Sn5oCl5Yi25Yqo5pe25Yi56L2m6LiP5p2/5pSv5p625YWo6YOo5pat6KOC77yM6L+Z56eN5Zyo5p6B6ZmQ5ouJ6ZSv5LiL556s6Ze05bSp5aGM55qE54mp55CG56ep5bqP77yM6YCP552A5a+55bel5Lia5bqV57q/5aSx5a6I55qE6K695Yi644CC5b2T5a6j5Lyg6YeM55qE5Y2O5Li66YCU54G16b6Z6KGM5bmz5Y+w6L+Y5Zyo5by66LCD5pm66am+5LiO5L6b55S157O757uf55qE57K+5a+G5Y2P5L2c5pe277yM5pyA5Z+656GA55qE5Lq65Yqb5py65qKw5YWc5bqV6YOo5Lu25Y205Zyo6L+e57ut6YeN5Yi55Lit546H5YWI5aSx5pWI44CCXG5cbuecn+ato+eahOWuieWFqOWumuWKm+S4jeaYr+WcqOmhuuWig+S4reS6q+WPl+eUteWtkOmFjee9rueahOWghuaWme+8jOiAjOaYr+WcqOinhOWImeWPmOWKqOaXtuS+neeEtuacieW6leawlOWuiOS9j+S4k+S4mueahOi+ueeVjOOAgumdouWvueaWreijguWQjuS7jjM457Gz5pq05aKe6IezMTQw57Gz55qE5Yi25Yqo6Led56a777yM5Lul5Y+K5L2O5LqO5Zu95qCHMjAwME7opoHmsYLnmoQxNjEyTuWPl+WKm+aVsOaNru+8jOi/meenjeS4jeS4uuefreacn+a1gemHj+WmpeWNj+eUn+WtmOW6lee6v+eahOWBmuazle+8jOavlOS7u+S9leeyvuS/rueahOa7pOmVnOmDveabtOacieivtOacjeWKm+OAglxuXG7mhL/ov5nku73pnIfliqjog73orqnlkI7mnaXogIXmmI7nmb3vvIznnJ/mraPnmoTpq5jnuqfmhJ/kuI3mmK/pnaDlj6Plj7fnmoTllqflmqPloIbnoIzvvIzogIzmmK/pnaDlr7npgqPkupvnu4/lvpfotbfmjqjmlbLnmoTnu4boioLnmoTpqbvotrPjgILlnKjkv6Hmga/niIbngrjnmoTlvZPkuIvvvIzkvp3nhLbmnInkurrmhL/mhI/kuLrov5nnp43lnKjlup/lop/kuIrph43lu7roh6rmiJHnp6nluo/mhJ/nmoTku6Pku7fkubDljZXjgIIj5bCK55WMVjgwMOWIuei9pui4j+adv+aUr+aetuaWreijgiMgIiwicmVnaW9uX25hbWUiOiLlj5HluIPkuo4g6ZmV6KW/Iiwib2siOjF9fQ==$evidence$, 'base64');
  provider_response jsonb;
  full_body text;
  current_record core.canonical_records%ROWTYPE;
  before_record jsonb;
  evidence jsonb;
  raw_evidence jsonb;
  raw_hash text;
  content_hash text;
  next_title text;
  run_id uuid := gen_random_uuid();
  source_id uuid := gen_random_uuid();
  connector constant text := 'manual:tikhub-weibo-long-text';
  stream constant text := 'weibo.post_detail.repair.v1';
BEGIN
  IF encode(sha256(exact_bytes), 'hex') <> response_hash THEN
    RAISE EXCEPTION 'Weibo repair evidence checksum mismatch';
  END IF;
  provider_response := convert_from(exact_bytes, 'UTF8')::jsonb;
  full_body := btrim(provider_response #>> '{data,longText,content}');
  IF provider_response ->> 'code' IS DISTINCT FROM '200'
     OR provider_response ->> 'request_id' IS DISTINCT FROM provider_request
     OR provider_response #>> '{data,idstr}' IS DISTINCT FROM '5351726865449966'
     OR provider_response #>> '{data,user,idstr}' IS DISTINCT FROM '2471317784'
     OR provider_response #>> '{data,isLongText}' IS DISTINCT FROM 'true'
     OR provider_response #>> '{params,is_get_long_text}' IS DISTINCT FROM 'true'
     OR full_body IS NULL OR char_length(full_body) <> 411
     OR btrim(provider_response #>> '{data,text_raw}') IS DISTINCT FROM full_body THEN
    RAISE EXCEPTION 'Weibo repair evidence identity or full-text fields mismatch';
  END IF;

  SELECT * INTO current_record FROM core.canonical_records WHERE id=target_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE NOTICE 'Weibo repair skipped: target record absent in this database';
    RETURN;
  END IF;
  IF current_record.dataset_id <> 'night-all.search.v1' OR current_record.platform <> 'weibo'
     OR current_record.object_type <> 'post' OR current_record.external_id <> '5351726865449966'
     OR current_record.author_external_id IS DISTINCT FROM '2471317784'
     OR current_record.deleted_at IS NOT NULL THEN
    RAISE EXCEPTION 'Weibo repair refused: canonical identity changed or deleted';
  END IF;
  IF current_record.extensions #>> '{weiboLongTextRepair,responseSha256}' = response_hash
     AND current_record.body = full_body THEN
    RAISE NOTICE 'Weibo repair already applied';
    RETURN;
  END IF;
  IF current_record.body IS DISTINCT FROM full_body
     AND NOT coalesce(core.weibo_long_text_preview_of(full_body, current_record.body), false) THEN
    RAISE EXCEPTION 'Weibo repair refused: current body is no longer the verified preview';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM core.record_revisions WHERE record_id=target_id
      AND revision=current_record.current_revision AND payload_sha256=current_record.payload_sha256) THEN
    RAISE EXCEPTION 'Weibo repair refused: current revision history is missing or inconsistent';
  END IF;
  before_record := to_jsonb(current_record);
  next_title := CASE WHEN current_record.title = current_record.body THEN full_body ELSE current_record.title END;
  evidence := jsonb_build_object('parserVersion','mxih-weibo-long-text-repair.v1',
    'provider','tikhub','endpoint','/api/v1/weibo/web_v2/fetch_post_detail',
    'params',jsonb_build_object('id','5351726865449966','is_get_long_text',true),
    'requestId',provider_request,'responseSha256',response_hash,'capturedAt',captured_at,
    'previousRevision',current_record.current_revision,'previousPayloadSha256',current_record.payload_sha256,
    'billingSource','supplier-direct-user-authorized','migration','131_weibo_long_text_and_lcy_grants.sql');
  raw_evidence := jsonb_build_object('response',provider_response,
    'exactResponseBase64',encode(exact_bytes,'base64'),'evidence',evidence,'previousCanonical',before_record);
  raw_hash := encode(sha256(convert_to(raw_evidence::text,'UTF8')),'hex');
  content_hash := encode(sha256(convert_to(jsonb_build_object('body',full_body,'title',next_title,
    'previousPayloadSha256',current_record.payload_sha256,'evidence',evidence)::text,'UTF8')),'hex');

  INSERT INTO ingest.ingest_runs(id,connector_id,stream_id,trigger,item_count,finished_at)
    VALUES(run_id,connector,stream,'manual_full_text_repair',1,now());
  INSERT INTO ingest.source_objects(id,connector_id,stream_id,object_type,source_key,
      payload_sha256,raw_payload_hash_version,raw_payload,source_updated_at,ingest_run_id)
    VALUES(source_id,connector,stream,'post','5351726865449966:'||response_hash,
      raw_hash,1,raw_evidence,captured_at,run_id);
  INSERT INTO ingest.source_object_revisions(source_object_id,revision,payload_sha256,payload_hash_version,
      raw_payload,source_updated_at,ingest_run_id)
    VALUES(source_id,1,raw_hash,1,raw_evidence,captured_at,run_id);
  UPDATE core.canonical_records SET title=next_title,body=full_body,
      extensions=extensions||jsonb_build_object('weiboLongTextRepair',evidence),payload_sha256=content_hash,
      current_revision=current_revision+1,projection_revision=projection_revision+1
    WHERE id=target_id RETURNING * INTO current_record;
  INSERT INTO core.record_revisions(record_id,revision,payload_sha256,normalized_payload,parser_version,ingest_run_id)
    VALUES(target_id,current_record.current_revision,content_hash,to_jsonb(current_record),'mxih-weibo-long-text-repair.v1',run_id);
  INSERT INTO core.observations(id,record_id,connector_id,source_event_id,observed_at,observation_hash,ingest_run_id)
    VALUES(gen_random_uuid(),target_id,connector,provider_request,captured_at,response_hash,run_id);
  INSERT INTO outbox.projection_events(aggregate_type,aggregate_id,event_type,projection_revision,payload)
    VALUES('canonical_record',target_id,'upsert',current_record.projection_revision,
      jsonb_build_object('datasetId',current_record.dataset_id,'platform','weibo','objectType','post'));
  RAISE NOTICE 'Weibo repaired: % characters, revision %, projection %',
    char_length(full_body),current_record.current_revision,current_record.projection_revision;
END
$repair$;

DO $grants$
DECLARE
  tenant constant uuid := '277bf8a4-5ed5-414d-b429-d72fcd7d36b6';
  consumer constant uuid := 'be7d07fe-3d98-4db3-b00d-e5cbe5a76190';
  selected_key api_keys%ROWTYPE;
  baseline api_key_platform_entitlements%ROWTYPE;
  previous_scopes jsonb;
  next_scopes jsonb;
  capability_name text;
  operations constant text[] := ARRAY['native.t.weibo_web_v2_fetch_realtime_search','native.t.api_4f35621a9c07e539'];
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('tenant-access:'||tenant::text));
  IF NOT EXISTS(SELECT 1 FROM consumers WHERE id=consumer AND tenant_id=tenant) THEN
    RAISE NOTICE 'LCY Weibo grant skipped: original consumer absent in this database';
    RETURN;
  END IF;
  IF NOT EXISTS(SELECT 1 FROM tenants WHERE id=tenant AND status='active')
     OR NOT EXISTS(SELECT 1 FROM consumers WHERE id=consumer AND status='active') THEN
    RAISE EXCEPTION 'LCY Weibo grant refused: original tenant/consumer is inactive';
  END IF;
  IF (SELECT count(*) FROM api_keys WHERE tenant_id=tenant AND consumer_id=consumer
      AND name='LCY-delta' AND id::text LIKE 'fd2f8cc9-%') <> 1 THEN
    RAISE EXCEPTION 'LCY Weibo grant refused: original Key missing or ambiguous';
  END IF;
  SELECT * INTO selected_key FROM api_keys WHERE tenant_id=tenant AND consumer_id=consumer
    AND name='LCY-delta' AND id::text LIKE 'fd2f8cc9-%' FOR UPDATE;
  IF selected_key.status <> 'active' OR selected_key.environment <> 'live'
     OR selected_key.scope_mode <> 'snapshot' OR selected_key.expires_at IS NULL
     OR selected_key.expires_at <= now() THEN
    RAISE EXCEPTION 'LCY Weibo grant refused: original Key is unavailable';
  END IF;
  IF EXISTS(SELECT 1 FROM api_keys WHERE consumer_id=consumer AND id<>selected_key.id
      AND status='active' AND scope_mode='legacy_dynamic') THEN
    RAISE EXCEPTION 'LCY Weibo grant refused: a sibling dynamic Key could inherit new grants';
  END IF;
  SELECT * INTO baseline FROM api_key_platform_entitlements WHERE api_key_id=selected_key.id AND platform='weibo';
  IF NOT FOUND THEN RAISE EXCEPTION 'LCY Weibo grant requires original Weibo quota snapshot'; END IF;
  previous_scopes := jsonb_build_object('scopeMode',selected_key.scope_mode,'webSearchOrder',selected_key.web_search_order,
    'platforms',(SELECT coalesce(jsonb_agg(platform ORDER BY platform),'[]') FROM api_key_platform_entitlements WHERE api_key_id=selected_key.id),
    'capabilities',(SELECT coalesce(jsonb_agg(capability ORDER BY capability),'[]') FROM api_key_capability_entitlements WHERE api_key_id=selected_key.id));

  PERFORM pg_advisory_xact_lock(hashtext(consumer::text||':authorization:platform:social'));
  INSERT INTO platform_grants(consumer_id,platform) VALUES(consumer,'social') ON CONFLICT DO NOTHING;
  INSERT INTO consumer_platform_policies(tenant_id,consumer_id,platform,max_requests,window_seconds,max_page_size)
    VALUES(tenant,consumer,'social',baseline.max_requests,baseline.window_seconds,baseline.max_page_size) ON CONFLICT DO NOTHING;
  INSERT INTO api_key_platform_entitlements(api_key_id,platform,max_requests,window_seconds,max_page_size)
    SELECT selected_key.id,'social',least(max_requests,baseline.max_requests),greatest(window_seconds,baseline.window_seconds),
      least(max_page_size,baseline.max_page_size) FROM consumer_platform_policies WHERE consumer_id=consumer AND platform='social'
    ON CONFLICT DO NOTHING;
  FOREACH capability_name IN ARRAY operations LOOP
    PERFORM pg_advisory_xact_lock(hashtext(consumer::text||':authorization:capability:'||capability_name));
    INSERT INTO capability_grants(consumer_id,capability) VALUES(consumer,capability_name) ON CONFLICT DO NOTHING;
    INSERT INTO consumer_capability_policies(tenant_id,consumer_id,capability,max_requests,window_seconds)
      VALUES(tenant,consumer,capability_name,baseline.max_requests,baseline.window_seconds) ON CONFLICT DO NOTHING;
    INSERT INTO api_key_capability_entitlements(api_key_id,capability,max_requests,window_seconds)
      SELECT selected_key.id,capability_name,least(max_requests,baseline.max_requests),greatest(window_seconds,baseline.window_seconds)
        FROM consumer_capability_policies WHERE consumer_id=consumer AND capability=capability_name ON CONFLICT DO NOTHING;
  END LOOP;
  next_scopes := jsonb_build_object('scopeMode',selected_key.scope_mode,'webSearchOrder',selected_key.web_search_order,
    'platforms',(SELECT coalesce(jsonb_agg(platform ORDER BY platform),'[]') FROM api_key_platform_entitlements WHERE api_key_id=selected_key.id),
    'capabilities',(SELECT coalesce(jsonb_agg(capability ORDER BY capability),'[]') FROM api_key_capability_entitlements WHERE api_key_id=selected_key.id));
  IF next_scopes IS DISTINCT FROM previous_scopes THEN
    INSERT INTO api_key_scope_events(api_key_id,actor,previous_scopes,next_scopes)
      VALUES(selected_key.id,'migration-131:user-authorized-weibo',previous_scopes,next_scopes);
  END IF;
  RAISE NOTICE 'LCY-delta original Key has social + Weibo native search/detail scopes; existing scopes/limits preserved';
END
$grants$;
