import { WEB_SEARCH_PROVIDERS } from '../../shared/web-search.mjs'
export const webSearchGuide = '<h2>Web Search</h2><p>先读取 capabilities，取得当前 Hub Key 开放的渠道和顺序。POST search 提交 query；省略 provider 使用该顺序，指定 provider 只调用该渠道。新租户和 Key 默认不开放，需管理员授权；新增渠道不会自动加入已有 Key。</p><p>每个请求需要 Idempotency-Key。同一 Key、同一语义请求和同一标识回放原交付。发送后不会因超时、空结果或失败自动切换渠道。未知结果先核对原请求，避免重复消费。</p><p>百度支持 web/image/video，每类上限分别 50/30/10，总量受 Key 分页额度限制；sites 和 from/to 日期范围、recency、edition 目前仅在百度执行。其他渠道当前仅支持网页、最多 20 条。不支持的条件不会静默丢弃。返回 data.provider、data.items 和 meta.capturedAt；结果为摘要和链接，不生成 AI 答案、不抓取全文。</p><p>compatible/baidu 只接受一个 user message，将百度请求形状转换为 Hub 统一结果，不承诺原生响应完全兼容。仅显式 provider=baidu 的统一请求与该入口在语义相同时共用幂等交付。API Key 使用 Hub Key；凭据和网络设置在管理端维护。</p>'
const base={tags:['Web Search'],'x-mx-required-platform':'web_search','x-mx-required-capabilities':['web.search'],'x-mx-doc-path':'/docs/web-search'}
const responses={'200':{description:'Unified result: data.query, data.provider, data.items[{type,title,url,snippet,publishedAt}], meta.capturedAt/empty/fullText'},'400':{description:'Invalid or unsupported options'},'403':{description:'Scope not granted'},'409':{description:'Idempotency conflict, request in progress or unknown outcome'},'503':{description:'No ready authorized channel'}}
const parameter={name:'Idempotency-Key',in:'header',required:true,schema:{type:'string',minLength:8,maxLength:128}}
export const webSearchPaths={
  '/data/web-search/search':{post:{...base,operationId:'webSearch',summary:'全网搜索',description:'显式提交一次搜索；支持渠道顺序和固定渠道。',parameters:[parameter],'x-mx-meter-key':'web.search',requestBody:{required:true,content:{'application/json':{example:{query:'人工智能',limit:10},schema:{type:'object',required:['query'],additionalProperties:false,properties:{query:{type:'string',minLength:1,maxLength:2000},provider:{type:'string',enum:WEB_SEARCH_PROVIDERS.map(p=>p.key)},limit:{type:'integer',minimum:1,maximum:50,default:10},resources:{type:'array',minItems:1,maxItems:3,description:'与 limit 二选一；每项 type 和 limit。',items:{type:'object',required:['type','limit'],additionalProperties:false,properties:{type:{type:'string',enum:['web','image','video']},limit:{type:'integer',minimum:1,maximum:50}}}},edition:{type:'string',enum:['standard','lite'],default:'standard'},sites:{type:'array',maxItems:20,items:{type:'string'}},from:{type:'string',format:'date'},to:{type:'string',format:'date'},recency:{type:'string',enum:['week','month','semiyear','year','noTimeLimit']}}}}}},responses}},
  '/data/web-search/capabilities':{get:{...base,operationId:'webSearchCapabilities',summary:'当前 Key 的搜索渠道与顺序',description:'只读元数据，不触发搜索。',responses:{'200':{description:'data.order and data.providers[{key,label,resources,maxResults,ready}]'}}}},
  '/data/web-search/compatible/baidu':{post:{...base,'x-mx-required-capabilities':['web.search','web.search.provider.baidu'],operationId:'webSearchBaiduInput',summary:'百度请求形状接入 · Hub 统一响应',parameters:[parameter],'x-mx-meter-key':'web.search',requestBody:{required:true,content:{'application/json':{example:{messages:[{role:'user',content:'人工智能'}],resource_type_filter:[{type:'web',top_k:10}],edition:'standard'},schema:{type:'object',required:['messages'],properties:{messages:{type:'array',minItems:1,maxItems:1,items:{type:'object',required:['role','content'],properties:{role:{type:'string',enum:['user']},content:{type:'string',minLength:1,maxLength:2000}}}},resource_type_filter:{type:'array',maxItems:3,items:{type:'object',properties:{type:{type:'string',enum:['web','image','video']},top_k:{type:'integer'}}}},edition:{type:'string',enum:['standard','lite']},search_filter:{type:'object'},search_recency_filter:{type:'string',enum:['week','month','semiyear','year','noTimeLimit']}}}}}},responses}},
}
