/**
 * Public mx-auto-server configuration is deliberately namespaced MX_AUTO_*.
 * The V0 kernel still reads MXT_*, so this boundary is the only compatibility
 * translation. It can disappear when the kernel moves behind its own package.
 */
export const ENVIRONMENT_MAP = Object.freeze({
  MX_AUTO_HOST: 'MXT_HOST',
  MX_AUTO_PORT: 'MXT_PORT',
  MX_AUTO_STORE: 'MXT_STORE',
  MX_AUTO_DATABASE_URL: 'MXT_DATABASE_URL',
  MX_AUTO_ADMIN_TOKEN: 'MXT_ADMIN_TOKEN',
  MX_AUTO_ARTIFACTS_DIR: 'MXT_ARTIFACTS_DIR',
  MX_AUTO_SELF_URL: 'MXT_SELF_URL',
  MX_AUTO_NAMESPACE: 'MXT_NAMESPACE',
  MX_AUTO_PUBLIC_URL: 'MXT_PUBLIC_URL',
  MX_AUTO_INSECURE_COOKIES: 'MXT_INSECURE_COOKIES',
  MX_AUTO_DEFAULT_ROLE: 'MXT_DEFAULT_ROLE',
  MX_AUTO_ARTIFACT_RETAIN_DAYS: 'MXT_ARTIFACT_RETAIN_DAYS',
  MX_AUTO_ARTIFACT_MAX_FILE_BYTES: 'MXT_ARTIFACT_MAX_FILE_BYTES',
  MX_AUTO_ARTIFACT_MAX_RUN_BYTES: 'MXT_ARTIFACT_MAX_RUN_BYTES',
  MX_AUTO_ARTIFACT_MAX_FILES_PER_RUN: 'MXT_ARTIFACT_MAX_FILES_PER_RUN',
  MX_AUTO_ARTIFACT_MAX_TOTAL_BYTES: 'MXT_ARTIFACT_MAX_TOTAL_BYTES',
  MX_AUTO_ARTIFACT_MAX_TOTAL_ENTRIES: 'MXT_ARTIFACT_MAX_TOTAL_ENTRIES',
  MX_AUTO_ARTIFACT_MIN_FREE_BYTES: 'MXT_ARTIFACT_MIN_FREE_BYTES',
  MX_AUTO_ARTIFACT_MIN_FREE_INODES: 'MXT_ARTIFACT_MIN_FREE_INODES',
  MX_AUTO_SCHEDULER_INTERVAL_MS: 'MXT_SCHEDULER_INTERVAL_MS',
  MX_AUTO_RUN_LEASE_MS: 'MXT_RUN_LEASE_MS',
  MX_AUTO_DEFAULT_TIMEZONE: 'MXT_DEFAULT_TIMEZONE',
  MX_AUTO_LAUNCHER_URL: 'MXT_LAUNCHER_URL',
  MX_AUTO_LAUNCHER_AUDIENCE: 'MXT_LAUNCHER_AUDIENCE',
  MX_AUTO_LAUNCHER_NEGATIVE_CACHE_TTL_MS: 'MXT_LAUNCHER_NEGATIVE_CACHE_TTL_MS',
  MX_AUTO_LAUNCHER_INTROSPECTION_WINDOW_MS: 'MXT_LAUNCHER_INTROSPECTION_WINDOW_MS',
  MX_AUTO_LAUNCHER_INTROSPECTION_MAX_STARTS: 'MXT_LAUNCHER_INTROSPECTION_MAX_STARTS',
  MX_AUTO_LAUNCHER_INTROSPECTION_MAX_IN_FLIGHT: 'MXT_LAUNCHER_INTROSPECTION_MAX_IN_FLIGHT',
  MX_AUTO_LAUNCHER_INTROSPECTION_MAX_STARTS_PER_SOURCE: 'MXT_LAUNCHER_INTROSPECTION_MAX_STARTS_PER_SOURCE',
  MX_AUTO_LAUNCHER_INTROSPECTION_MAX_IN_FLIGHT_PER_SOURCE: 'MXT_LAUNCHER_INTROSPECTION_MAX_IN_FLIGHT_PER_SOURCE',
  MX_AUTO_LAUNCHER_PASSWORD_LOGIN_WINDOW_MS: 'MXT_LAUNCHER_PASSWORD_LOGIN_WINDOW_MS',
  MX_AUTO_LAUNCHER_PASSWORD_LOGIN_MAX_STARTS: 'MXT_LAUNCHER_PASSWORD_LOGIN_MAX_STARTS',
  MX_AUTO_LAUNCHER_PASSWORD_LOGIN_MAX_IN_FLIGHT: 'MXT_LAUNCHER_PASSWORD_LOGIN_MAX_IN_FLIGHT',
  MX_AUTO_LAUNCHER_PASSWORD_LOGIN_MAX_STARTS_PER_SOURCE: 'MXT_LAUNCHER_PASSWORD_LOGIN_MAX_STARTS_PER_SOURCE',
  MX_AUTO_LAUNCHER_PASSWORD_LOGIN_MAX_IN_FLIGHT_PER_SOURCE: 'MXT_LAUNCHER_PASSWORD_LOGIN_MAX_IN_FLIGHT_PER_SOURCE',
  MX_AUTO_GIT_TOKEN_SECRET: 'MXT_GIT_TOKEN_SECRET',
  MX_AUTO_GIT_TOKEN_SECRET_KEY: 'MXT_GIT_TOKEN_SECRET_KEY',
  MX_AUTO_SECRET_KEY: 'MXT_SECRET_KEY',
  MX_AUTO_WORKSPACE_SIZE_LIMIT: 'MXT_WORKSPACE_SIZE_LIMIT',
  MX_AUTO_RUNNER_ARTIFACT_SIZE_LIMIT: 'MXT_RUNNER_ARTIFACT_SIZE_LIMIT',
  MX_AUTO_MAX_CONCURRENT_SERVER_RUNS: 'MXT_MAX_CONCURRENT_SERVER_RUNS',
  MX_AUTO_RUNNER_CPU_REQUEST: 'MXT_RUNNER_CPU_REQUEST',
  MX_AUTO_RUNNER_CPU_LIMIT: 'MXT_RUNNER_CPU_LIMIT',
  MX_AUTO_RUNNER_MEMORY_REQUEST: 'MXT_RUNNER_MEMORY_REQUEST',
  MX_AUTO_RUNNER_MEMORY_LIMIT: 'MXT_RUNNER_MEMORY_LIMIT',
  MX_AUTO_RUNNER_EPHEMERAL_STORAGE_REQUEST: 'MXT_RUNNER_EPHEMERAL_STORAGE_REQUEST',
  MX_AUTO_RUNNER_EPHEMERAL_STORAGE_LIMIT: 'MXT_RUNNER_EPHEMERAL_STORAGE_LIMIT',
  MX_AUTO_RUNNER_IMAGE_CYPRESS: 'MXT_RUNNER_IMAGE_CYPRESS',
  MX_AUTO_RUNNER_IMAGE_PLAYWRIGHT: 'MXT_RUNNER_IMAGE_PLAYWRIGHT',
  MX_AUTO_RUNNER_IMAGE_PYTEST: 'MXT_RUNNER_IMAGE_PYTEST',
  MX_AUTO_RUNNER_IMAGE_K6: 'MXT_RUNNER_IMAGE_K6',
  MX_AUTO_RUNNER_IMAGE_GENERIC: 'MXT_RUNNER_IMAGE_GENERIC'
})

const DEFAULTS = Object.freeze({
  MXT_NAMESPACE: 'mx-auto',
  MXT_SELF_URL: 'http://mx-auto-server',
  MXT_LAUNCHER_AUDIENCE: 'mx-sdk',
  MXT_LAUNCHER_NEGATIVE_CACHE_TTL_MS: '3000',
  MXT_LAUNCHER_INTROSPECTION_WINDOW_MS: '10000',
  MXT_LAUNCHER_INTROSPECTION_MAX_STARTS: '30',
  MXT_LAUNCHER_INTROSPECTION_MAX_IN_FLIGHT: '8',
  MXT_LAUNCHER_INTROSPECTION_MAX_STARTS_PER_SOURCE: '6',
  MXT_LAUNCHER_INTROSPECTION_MAX_IN_FLIGHT_PER_SOURCE: '2',
  MXT_LAUNCHER_PASSWORD_LOGIN_WINDOW_MS: '10000',
  MXT_LAUNCHER_PASSWORD_LOGIN_MAX_STARTS: '10',
  MXT_LAUNCHER_PASSWORD_LOGIN_MAX_IN_FLIGHT: '4',
  MXT_LAUNCHER_PASSWORD_LOGIN_MAX_STARTS_PER_SOURCE: '3',
  MXT_LAUNCHER_PASSWORD_LOGIN_MAX_IN_FLIGHT_PER_SOURCE: '1',
  MXT_GIT_TOKEN_SECRET: 'mx-auto-secrets',
  MXT_GIT_TOKEN_SECRET_KEY: 'MX_AUTO_GIT_TOKEN'
})

export function mapExternalEnvironment(source = process.env, target = process.env) {
  for (const [externalName, kernelName] of Object.entries(ENVIRONMENT_MAP)) {
    if (Object.prototype.hasOwnProperty.call(source, externalName)) {
      target[kernelName] = String(source[externalName] ?? '')
    } else {
      // A shell that previously ran the legacy service may still contain MXT_*
      // values. They are not public configuration for this service and must
      // not silently point a runner back at the legacy namespace or database.
      delete target[kernelName]
    }
  }
  for (const [kernelName, value] of Object.entries(DEFAULTS)) {
    if (!target[kernelName]?.trim()) target[kernelName] = value
  }
  // MX Auto is exposed directly over plain HTTP by its local server and the
  // bundled NodePort. When no advertised URL was supplied, the legacy kernel
  // cannot infer that scheme and would otherwise emit a Secure session cookie
  // that browsers silently drop. An explicit cookie setting or public URL
  // continues to win.
  if (!target.MXT_INSECURE_COOKIES?.trim() && !target.MXT_PUBLIC_URL?.trim()) {
    target.MXT_INSECURE_COOKIES = 'true'
  }
  return target
}
