apiVersion: v1
kind: Namespace
metadata:
  name: mx-internal-shadow
  labels:
    app.kubernetes.io/name: mx-launcher
    app.kubernetes.io/part-of: mx-3ks
    mx.qpjoy.com/environment: shadow
    mx.qpjoy.com/site-role: internal
