apiVersion: v1
kind: ServiceAccount
metadata:
  name: mx-launcher-internal
  namespace: mx-internal-shadow
  labels:
    app.kubernetes.io/name: mx-launcher-internal
    app.kubernetes.io/part-of: mx-3ks
