apiVersion: v1
kind: Namespace
metadata:
  name: mx-dns
  labels:
    app.kubernetes.io/name: mx-dns
    app.kubernetes.io/part-of: mx-3ks
    mx.qpjoy.com/environment: shadow
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: mx-dns
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/part-of: mx-3ks
    mx.qpjoy.com/component: dns-control
    mx.qpjoy.com/environment: shadow
data:
  Corefile: |
    .:53 {
      errors
      health
      ready
      cache 30
      forward . /etc/resolv.conf
    }
  mx-zone-snapshot.json: "{}"
