const escape = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export interface AccountChoice { reference: string; account: string; name: string; current: boolean; available: boolean; admissionRequired?: boolean }
export function accountsPage(input: { action: string; csrf: string; appName: string; returnUrl: string; entries: AccountChoice[]; message?: string }) {
  const action = escape(input.action);
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>选择账号 · ${escape(input.appName)}</title><style>
  :root{color-scheme:dark;--bg:#141417;--panel:#21232d;--line:#3c4658;--text:#e2e2e2;--muted:#a7b3bf;--accent:#2bf6d2;--hover:#292e3a}
  *{box-sizing:border-box}body{margin:0;min-height:100svh;display:grid;place-items:center;padding:24px;background:var(--bg);color:var(--text);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}
  main{width:100%;max-width:480px;padding:32px;border:1px solid var(--line);border-radius:18px;background:var(--panel)}.brand{display:flex;align-items:center;gap:12px;font-weight:600}.mark{display:grid;place-items:center;width:38px;height:38px;border-radius:11px;background:var(--accent);color:var(--bg);font-weight:800}h1{font-size:26px;letter-spacing:-.02em;line-height:1.3;margin:26px 0 8px}.intro{color:var(--muted);margin:0 0 24px}ul{list-style:none;margin:0;padding:0;border-top:1px solid var(--line)}li{display:flex;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}form{margin:0;min-width:0}.account{flex:1}button,a{font:inherit;color:var(--accent)}button{cursor:pointer;border:0;background:transparent;border-radius:9px;min-height:44px;padding:8px}button:hover,a.choice:hover{background:var(--hover)}button:disabled{cursor:default;opacity:.55}button:focus-visible,a:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.choice{display:flex;align-items:center;gap:12px;width:100%;text-decoration:none;padding:12px 8px;color:var(--text);border-radius:9px;text-align:left}.avatar{flex:none;display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:var(--hover);color:var(--accent);font-size:18px;font-weight:600}.identity{min-width:0;flex:1}.identity strong,.identity small{display:block;overflow-wrap:anywhere}.identity small{color:var(--muted);font-size:12px}.state{font-size:12px;color:var(--accent);white-space:nowrap}.add{margin-top:16px;color:var(--accent)}footer{border-top:1px solid var(--line);padding-top:20px;margin-top:24px;display:flex;justify-content:space-between;gap:16px;font-size:12px;color:var(--muted)}footer a{color:var(--accent);text-decoration:none}.message{color:var(--muted)}
  @media(prefers-color-scheme:light){:root{color-scheme:light;--bg:#f3f7fa;--panel:#fff;--line:#d4dfe6;--text:#192b3a;--muted:#657584;--accent:#008d82;--hover:#edf4f6}.mark{color:#fff}}
  @media(max-width:480px){body{padding:16px}main{padding:24px 20px}footer{flex-wrap:wrap}}
  </style></head><body><main><div class="brand"><span class="mark" aria-hidden="true">MX</span><span>${escape(input.appName)}</span></div><h1>选择账号</h1><p class="intro">继续进入 ${escape(input.appName)}</p>
  ${input.message ? `<p role="status" class="message">${escape(input.message)}</p>` : ''}
  ${input.entries.length ? `<ul>${input.entries.map(entry => `<li>
    <form class="account" method="post" action="${action}"><input type="hidden" name="csrf" value="${escape(input.csrf)}"><input type="hidden" name="account" value="${escape(entry.reference)}"><button class="choice" name="intent" value="choose" ${entry.available || entry.admissionRequired ? '' : 'disabled'}><span class="avatar" aria-hidden="true">${escape(Array.from(entry.name || entry.account)[0] || 'M')}</span><span class="identity"><strong>${escape(entry.name || entry.account)}</strong><small>${escape(entry.account)}</small></span><span class="state">${entry.admissionRequired ? '填写邀请' : !entry.available ? '不可用' : entry.current ? '已登录 · 继续' : '重新登录'}</span></button></form>
    ${!entry.current ? `<form method="post" action="${action}"><input type="hidden" name="csrf" value="${escape(input.csrf)}"><input type="hidden" name="account" value="${escape(entry.reference)}"><button name="intent" value="remove" aria-label="移除 ${escape(entry.account)}">移除</button></form>` : ''}</li>`).join('')}</ul>` : '<p class="message">这个浏览器还没有记住的账号。</p>'}
  <a class="choice add" href="${action}?view=login"><span class="avatar" aria-hidden="true">＋</span>使用其他账号</a>
  <footer><span>仅记住此浏览器使用过的账号</span><a href="${escape(input.returnUrl)}">返回应用</a></footer></main></body></html>`;
}
